---
title: "Effects of the COVID-19 pandemic on economic well-being in the United States"
subtitle: ""
author: 
  - Roy Chan
thanks: "Code and data are available at: LINK."
date: "`r format(Sys.time(), '%d %B %Y')`"
abstract: "First sentence. Second sentence. Third sentence. Fourth sentence."
output:
  bookdown::pdf_document2
toc: FALSE
bibliography: references.bib
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

# Introduction

# Data
The survey data that is presented within this paper is obtained from the 2021 United States General Social Survey (GSS). 

## Survey methodology
The US GSS was created to collect long term public opinion and sentiment within the United States. The main component of the survey is the replicating core, a central set of questions repeated in each year the survey was conducted for the purpose of exploring trends in opinion over time (CITATION US GSS 2021). Additional modules present but not always consistently asked from year to year include topics relevant for the year. Examples of this for 2021 included but not limited to: attitudes towards policing, racial discrimination, and attitudes relating to trust in institutions and the government dealing with COVID-19. A major strength of the US GSS is in its long existence and replicating core, allowing tracking of contemporary sentiments over a significant period of time. Prior to 2021, surveys were administered in person in an interview format by an interviewer, which as noted by the 2021 codebook resulted in high response rates of above 50%. 

The target population of the GSS are adults over the age of 18 who lived in non-institutional housing at the time of taking the survey. The intention is to make the obtained sample an accurate representation of the national population of the United States, thus a stratified sampling method was chosen. Since 2004, the US GSS has used the sampling frame adapted from the list of postal addresses maintained by the United States Postal Service (USPS). Areas are categorised with respect to their population densities as either urban or rural.

However, a significant limitation as discussed in the GSS Cumulative Codebook (CITATION CUMULATIVE CODEBOOK) it is more often the case that urban and rural areas are interspersed. This causes difficulty for interviewers to effectively pursue interviewees, due to differences in density and ability to locate households in rural areas. From this, a multi-stage cluster sampling approach is applied. Firstly, stratification is performed- the entire sampling frame is grouped consisting of urban areas and one or more of its surrounding rural areas from which about half is selected. Secondly, each chosen area is divided into two segments according to whether they are part of a census tract or a block group. This allows for generating a high quality list of clustered addresses for interviewers to efficiently conduct the survey, reducing cost. 

As stated by the GSS Cumulative Codebook, as of 2004 non-response of the survey has been addressed through sub-sampling. For all of the households in the sample that were non-respondents, a proportion, typically 50%, of those who were labelled as temporary non-respondents were pursued again. As such, those responses were weighted at 2 for the sub-sample to represent the entirety of the temporary non-respondents.

### Methodology changes to 2021 GSS
Owing to the COVID-19 pandemic, the 2021 edition was primarily conducted through the web instead, with an alternative phone interview option. Participants were recruited through mail, who were then invited to complete the survey online. Given that this method was utilised, the consideration of an interviewer having to physically perform interviews was no longer required. Thus, a stratified non-clustered sampling approach was used for a greater sample size.

Another significant change was that treatment non-respondents was not handled

# Results
The survey data, along with the corresponding codebook, was retrieved from the GSS web portal (CITATION GSS WEBSITE). All analysis was performed in `R` [@citeR], with the data being read and prepared using `haven` [@citeHaven] and `dplyr` [@citeDplyr] respectively. Graphs were generated using `ggplot2` [@citeGgplot].

For the purpose of this paper, we will be focusing on the sub-section of economic well-being within the replicating core, specifically in the 2018 and 2021 US GSS.

# Discussion

## First discussion point


## Second discussion point

## Third discussion point

## Weaknesses and next steps

- difference in survey methodology
- survey format in person vs 
- 2021 codebook stating higher than normal non-response for factual information

\newpage

\appendix

# Supplementary survey


\newpage


# References


